# version: '3.8'
services:
  db:
    container_name: 'goChatDB'
    image: postgres:14-alpine
    volumes:
      - './database/postgres-data:/var/lib/postgresql/data:rw'
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: 'go_chat_db'
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
    restart: unless-stopped

  server:
    container_name: 'goChatServer'
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    volumes:
      - ./server:/app
    environment:
      - secretKey=your-secret-key-here
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=go_chat_db
    depends_on:
      - db
    restart: unless-stopped

  client:
    container_name: 'goChatClient'
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - ./client:/app
      - /app/node_modules # コンテナ内のnode_modulesを上書きさせない
    environment:
      - CHOKIDAR_USEPOLLING=true # ファイル変更検知を確実にする
    depends_on:
      - server
    restart: unless-stopped
